---
title: "Refugee Project - Final Presentation"
author: "R against the Machine"
date: "4/29/2019"
output: ioslides_presentation
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(recipes)
require(tidyverse)
require(pdp)
require(utf8)
require("skimr")
require(foreign)
require(readr)
library(haven)
require(scales)
require(dplyr)
require(reshape2)
 ASRraw <- read_dta("2016-ASR_Public_Use_File.dta") ##Loading main dataset
```

## Background

- Bullet 1
- Bullet 2
- Bullet 3

## Employment and Schooling

```{r}

```

## Benefits

```{r}
#### Steffi: I create a new dataframe with the variables in which I am interested (benefits) ##
ASR_ben <-
ASRraw %>%
select (qn30a, qn31a, qn32a, qn33a, qn34a)%>%
rename ("food"="qn30a") %>%  
rename ("tanf"="qn31a") %>% 
rename ("rca"="qn32a") %>% 
rename ("ssi"="qn33a") %>% 
rename ("ga"="qn34a")
 
### Steffi: Graphs ##
b1 <- ggplot(ASR_ben, aes(x = as.factor(food))) +
  labs(title = "Food Stamps") +
  geom_bar(position='dodge', width=.5, fill = "steelblue") +
  coord_flip() +
  scale_x_discrete(labels=c("1" = "No", "2" = "Yes",
                              "8" = "Don't know", "9" = "Refused")) +
  xlab("") +
  ylab("")

b2 <- ggplot(ASR_ben, aes(x = as.factor(tanf))) +
  labs(title = "TANF") +
  geom_bar(width=.5, fill = "steelblue") +
  coord_flip() +
  scale_x_discrete(labels=c("1" = "No", "2" = "Yes",
                              "8" = "Don't know", "9" = "Refused")) +
  xlab("") +
  ylab("")

b3 <- ggplot(ASR_ben, aes(x = as.factor(rca))) +
  labs(title = "RCA") +
  geom_bar(width=.5, fill = "steelblue") +
  coord_flip() +
    scale_x_discrete(labels=c("1" = "No", "2" = "Yes",
                              "8" = "Don't know", "9" = "Refused")) +
  xlab("") +
  ylab("")

b4 <- ggplot(ASR_ben, aes(x = as.factor(ssi))) +
  labs(title = "SSI") +
  geom_bar(width=.5, fill = "steelblue") +
  coord_flip() +
  scale_x_discrete(labels=c("1" = "No", "2" = "Yes",
                              "8" = "Don't know", "9" = "Refused")) + 
  xlab("") +
  ylab("")

b5 <- ggplot(ASR_ben, aes(x = as.factor(ga))) +
  labs(title = "GA") +
  geom_bar(width=.5, fill = "steelblue") +
  coord_flip() +
  scale_x_discrete(labels=c("1" = "No", "2" = "Yes",
                              "8" = "Don't know", "9" = "Refused")) +
  xlab("") +
  ylab("")

### creates multiplot ###
multiplot <- function(..., plotlist=NULL, file, cols=3, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
multiplot(b1, b2, b3, b4, b5, cols=2)
```

## Demographics

```{r}

```